## **Exemplos tópico 6.Estruturas de Decisão Condicionais**

In [71]:
#Estrutura do if
nota = float(input("Digite sua nota na disciplina:")) 
if nota < 6.0: 
  print('Reprovado!')

Digite sua nota na disciplina:6


In [72]:
#Estrutura do if..else
nota = float(input("Digite sua nota na disciplina:"))

if nota>= 6.0:
  print('Aprovado!')
else: # Atenção: Cuidado com a identação !
  print('Reprovado!')

Digite sua nota na disciplina:6
Aprovado!


In [73]:
#Estrutura do if...elif( else + if )...else
idade = int(input("Digite sua idade"))
if idade <3:
  print(Bebê)
elif idade <10: # Atenção: Cuidado com a identação!
  print('Infantil')
elif idade <14:
  print('Junior')
elif idade <18:
  print('Adolescente')
elif idade <30:
  print('Jovem')
else:
  print('Adulto')

Digite sua idade27
Jovem


## **Exemplos tópico 7.Estruturas de Repetição**

In [74]:
#Estrutura Laço While

senha = "54321"
leitura =" "

while (leitura != senha):
  leitura = input("Digite a senha:")
  if leitura == senha :
    print('Acesso liberado')
  else:
    print('Senha incorreta.Tente novamente')

Digite a senha:369852
Senha incorreta.Tente novamente
Digite a senha:54321
Acesso liberado


In [75]:
#Estrutura Laço While - Soma 5 valores

contador = 0 
somador = 0
while contador < 5:
  contador = contador + 1
  valor = float(input('Digite o '+str(contador)+'º valor:'))
  somador = somador + valor
print ('Soma = ',somador )

Digite o 1º valor:5
Digite o 2º valor:3
Digite o 3º valor:7
Digite o 4º valor:9
Digite o 5º valor:5
Soma =  29.0


In [ ]:
#Laço for
#O range eh gerado por causa de uma sequencia numerica

s=0
for x in range(1,20,3):
  s = s+x
print('Soma = ', s)


Soma =  70


In [76]:
Lista_notas= [3.4,6.6,8,9,10,9.5,8.8,4.3]

soma=0
for nota in Lista_notas:
  soma = soma+nota
media = soma/len(Lista_notas)
print('Média = ', ' {:.2f}'.format(media) )

Média =   7.45


In [77]:
def CalcMedia(lista):
  soma=0
  for nota in lista:
    soma = soma+nota
  return soma/len(lista)

Lista_notas= [3.4,6.6,8,9,10,9.5,8.8,4.3]
media = CalcMedia(Lista_notas)
print('Media =', '{:.2f}'.format(media))

Media = 7.45


In [78]:
def categoria(idade):
  if idade < 3:
    ctg = 'Bebê'
  elif idade < 10:
    ctg = 'Infantil'
  elif idade < 14:
    ctg = 'Junior'
  elif idade < 18:
    ctg = 'Adolescente'
  elif idade < 30:
    ctg = 'Jovem'
  else:
    ctg = 'Adulto'
    return ctg # Lembrar de identar o codigo corretamente; return dentro do else

idd = int(input("Digite sua idade:"))
print("Sua categoria é:", categoria(idd))   

Digite sua idade:33
Sua categoria é: Adulto


In [79]:
def categoria(idade):
  if idade < 3:
    ctg = 'Bebê'
  elif idade < 10:
    ctg = 'Infantil'
  elif idade < 14:
    ctg = 'Junior'
  elif idade < 18:
    ctg = 'Adolescente'
  elif idade < 30:
    ctg = 'Jovem'
  else: ctg = 'Adulto'
  return ctg

idd = int(input("Digite sua idade:"))
print("Sua categoria é:", categoria(idd)) 

Digite sua idade:60
Sua categoria é: Adulto


In [80]:
def MaiorValor(lista):
  if len(lista) > 0:
    maior = lista [0]
  else:
    maior = 0;
  for valor in lista:
    if valor > maior:
      maior = valor
  return maior

ListaNotas = [3.4,6.6,8,9,10,9.5,8.8,4.3]
resultado = MaiorValor(ListaNotas)
print (resultado)

10


In [81]:
def Leitura(lista,qtd):
  for i in range(1,qtd+1):
    lista.append(int(input("Digite o valor do elemento")))

ListaNotas = []
Leitura(ListaNotas,5)
print(ListaNotas)

Digite o valor do elemento2
Digite o valor do elemento5
Digite o valor do elemento3
Digite o valor do elemento4
Digite o valor do elemento1
[2, 5, 3, 4, 1]


In [82]:
def cria():
  d = {}
  return d

def inclui(d):
  nome = input("Digite o nome a incluir: ")
  if nome in d:
    print("Nome já existe não pode ser incluido")
  else:
    fone = input("Digite o fone:")
    d[nome]=fone

def consulta(d):
  nome = input("Digite o nome a consultar: ")
  print("Telefone: ",d.get(nome,'Não disponivel'))

def altera(d):
  nome = input("Digite o nome do fone a alterar: ")
  print("Telefone atual: ",d.get(nome,'Não disponivel' ))
  if nome in d:
    fone = input("Digite o novo fone: ")
    d[nome]=fone
    print("Telefone alterado!")
  else:
    print("Telefone não pode ser alterado !")

def exclui(d):
  nome = input("Digite o nome a excluir: ")
  if nome in d:
    del d[nome]
    print("Nome e fone excluidos !")
  else:
    print("Nome Inexistente !")

def mostra(d):
  print("Agenda:")
  for nome in d.keys():
    print(nome,d[nome])

agenda = cria()
inclui(agenda)
inclui(agenda)
inclui(agenda)
consulta(agenda)
altera(agenda)
exclui(agenda)
mostra(agenda)


Digite o nome a incluir: Veloso
Digite o fone:14333333
Digite o nome a incluir: Marcos
Digite o fone:11009898
Digite o nome a incluir: Luis
Digite o fone:09888877
Digite o nome a consultar: Marcos
Telefone:  11009898
Digite o nome do fone a alterar: 09888877
Telefone atual:  Não disponivel
Telefone não pode ser alterado !
Digite o nome a excluir: Veloso
Nome e fone excluidos !
Agenda:
Marcos 11009898
Luis 09888877


In [83]:
agenda = cria()
opc = 10
while opc!= 0:
  opc = int(input("Digite 0.Sair,1.INC,2.Con,3.Alt,4.Exc,5.Most:"))
  if opc ==1:
    inclui(agenda)
  elif opc == 2:
      consulta(agenda)
  elif opc == 3:
      aletra(agenda)
  elif opc == 4:
      exclui(agenda)
  elif opc == 5:
      mostra(agenda)
  elif opc == 0:
      print("Tchau,Tachu")
  else:
      print("Opção Inválida!")

Digite 0.Sair,1.INC,2.Con,3.Alt,4.Exc,5.Most:2
Digite o nome a consultar: Marcos
Telefone:  Não disponivel
Digite 0.Sair,1.INC,2.Con,3.Alt,4.Exc,5.Most:0
Tchau,Tachu


In [84]:
tempc = [23,18,32,16,21]
tempf = []
for i in tempc:
  tempf.append((i * 9/5) + 32)
print(tempc)
print(tempf)

[23, 18, 32, 16, 21]
[73.4, 64.4, 89.6, 60.8, 69.8]


In [85]:
tempc = [23,18,32,16,21]
tempf = list(map(lambda x: (x * 9/5)+ 32,tempc))
print(tempc)
print(tempf)

[23, 18, 32, 16, 21]
[73.4, 64.4, 89.6, 60.8, 69.8]


In [86]:
tempc = [23,18,32,16,21]
tempf = [(x*9/5)+ 32 for x in tempc]
print(tempc)
print(tempf)

[23, 18, 32, 16, 21]
[73.4, 64.4, 89.6, 60.8, 69.8]


In [87]:
s = 'tokenizar'
stk = [x for x in s]
print(s)
print(stk)

tokenizar
['t', 'o', 'k', 'e', 'n', 'i', 'z', 'a', 'r']


## **Exemplos tópico 8.NumPy**

In [88]:
import numpy as np

In [89]:
a = np.array([12,34,26,18,10])
# ira cria uma matriz unidimensional
print(a)
print(a.dtype)

[12 34 26 18 10]
int64


In [90]:
a1 = np.array([1, 2, 3], dtype = np.float64)
# cria um array como float de 64 bits
print(a1)
print(a1.dtype)

a2 = np.array([1, 2,3], dtype = np.int32)
# cria um array como float de 64 bits
print(a2)
print(a2.dtype)

[1. 2. 3.]
float64
[1 2 3]
int32


In [91]:
a3 = np.array([1.4, 3.6, -5.1, 9.42, 4.999999, 4.4, -9.0 ])
# tranformar tipo de dados de arrays
print(a3)
print(a3.dtype) # ira mostrar o array definido na variavel a3

a4 =a3.astype(np.int32)
# tranformar float para int ( os valores são truncados)
print(a4)
print(a4.dtype) # mostra o array a3 transformado para int na variavel a4

a5 = np.array([1, 7, 8, 9])
print(a5)
print(a5.dtype)

a6 = a5.astype(float)

#realizando de forma inversa

print(a6)
print(a6.dtype)


[ 1.4       3.6      -5.1       9.42      4.999999  4.4      -9.      ]
float64
[ 1  3 -5  9  4  4 -9]
int32
[1 7 8 9]
int64
[1. 7. 8. 9.]
float64


In [92]:
b = np.array([[7,98,23], [11,27,4], [999,34,23]])
print(b)

[[  7  98  23]
 [ 11  27   4]
 [999  34  23]]


In [93]:
import numpy as np
c = np.empty([3,2], dtype = int)
print(c)

[[3 3]
 [5 5]
 [7 7]]


In [94]:
d = np.zeros([4,3]) # ira criar uma matriz 4x3 com valores = 0 
print(d)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [95]:
e = np.ones([2,2]) # ira criar uma matriz 2x2 com valores = 1
print(e)

[[1. 1.]
 [1. 1.]]


In [96]:
f = np.eye(5) # ira criar uma matriz quadrada com a diagonal com valores =1 e os outros valores =0
print(f)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [97]:
g = np.random.random((5))
print(g)

[0.76654517 0.64747876 0.64924296 0.16870528 0.52994182]


In [98]:
g2= np.random.randn((5))
print(g2)

[-0.17482929  0.27743042 -1.85926076  0.31161634 -0.81525678]


In [99]:
h =np.floor(10*np.random.random((3,4)))
print(h)
h = (10*np.random.random((3,4)))
print (h)
h = np.floor(h)
print (h)

[[1. 7. 2. 3.]
 [7. 3. 6. 1.]
 [3. 3. 3. 2.]]
[[5.64620385 8.98087024 8.68492541 4.64610527]
 [2.42764784 0.01832383 6.77071148 4.97718746]
 [9.81491472 9.357615   8.46424036 9.49814548]]
[[5. 8. 8. 4.]
 [2. 0. 6. 4.]
 [9. 9. 8. 9.]]


In [100]:
gnr = np.random.default_rng(0)
i = gnr.random(3)
print(i)

[0.63696169 0.26978671 0.04097352]


In [101]:
 i = gnr.integers(10, size=(3,4))
 print(i)

[[0 0 1 8]
 [6 9 5 6]
 [9 7 6 5]]


In [102]:
j = np.array([11, 12, 12, 13, 14, 15, 16, 17,18, 19,20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [103]:
k = np.array([[17,22,43], [27,25,14],[15,24,32]]) # criação de uma matriz bidimensional denominada k
print(k)
print(k[0][1])
print(k.shape)
print(k.max())
print(k.min())
print(k.sum())
print(k.mean())
print(k.std()) # Desvio padrão dos valores da matriz k


[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)
43
14
219
24.333333333333332
8.615231988880057


In [104]:
k1 = np.array([1, 4, 9, 16, 25, 36])

print(np.sqrt(k1)) # raiz quadrada de todos os elementos
print(np.exp(k1)) # exponencial de todos os elementos

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [105]:
l = np.array([[4, 5],[6, 1],[7,4]])
print(l)
l_linha_1 =l[0, :]
print(l_linha_1)
l_linha_2 =l[1, :]
print(l_linha_2)
l_linha_3 =l[2, :]
print(l_linha_3)
l_linha_l =l[:, 0]
print(l_linha_1)
l_linha_2 = l[:, 1]
print(l_linha_2)

[[4 5]
 [6 1]
 [7 4]]
[4 5]
[6 1]
[7 4]
[4 5]
[5 1 4]


In [106]:
m = np.array([1, 2, 3, 4, 5, 6])
print(m[1]) # mostra o elemento da posição 2

print(m[0:2]) # mostra o array criado a partir da posição 0

print(m[1:]) # mostra o array criado a partir da 2a posição

print(m[-3:]) #mostra o array criado a partir da antepenultima posição até o final

2
[1 2]
[2 3 4 5 6]
[4 5 6]


In [107]:
n = np.array([[1, 2], [3,4]])
o = np.array([[1,1], [1,1]])
res1 = n+o 
print(res1)

res2 = n*o
print(res2)

[[2 3]
 [4 5]]
[[1 2]
 [3 4]]


In [108]:
p = np.array([[1, 2], [3, 4],[5,6]])
q = np.array([[2, 1]])
print(p+q)

[[3 3]
 [5 5]
 [7 7]]


In [109]:
r = np.arange(15).reshape((3, 5))
print(r)

s=r.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [110]:
r = np.arange(15).reshape((3, 5))
print(r)

# matrizes transposta entre linhas e colunas
s=r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [111]:
t = np.arange(16).reshape((2, 2, 4))
print(t)
# rearranjando as linhas
# trocamos de posição os eixos 0 e 1 do array
u = t.transpose((1, 0, 2))
print(u)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [112]:
t = np.arange(16).reshape((2, 2, 4))
print(t)

u = t.swapaxes(1, 2)
print(u)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [113]:
v = np.random.randn(4, 4)
print(v)
# matriz com valores positivos e negativos de forma aleatória
x =(v >0) 
# matriz com valores booleanos 
print(x)
z =np.where(x >0, 1, -1)
# matriz com valores -1 e 1 np array x
print(z)

[[-0.57652878 -0.13340039 -0.67929892  0.69686125]
 [-0.83310734 -0.75641096 -0.55527866  1.01860495]
 [-1.55180611 -0.02877086 -1.29228415  1.24586457]
 [ 0.99087991  0.24325346 -0.47186964 -0.65260922]]
[[False False False  True]
 [False False False  True]
 [False False False  True]
 [ True  True False False]]
[[-1 -1 -1  1]
 [-1 -1 -1  1]
 [-1 -1 -1  1]
 [ 1  1 -1 -1]]
