## **Exemplos tópico 6.Estruturas de Decisão Condicionais**

In [ ]:
  #Estrutura do if
nota = float(input("Digite sua nota na disciplina:"))

if nota < 6.0:
  print('Reprovado')

In [ ]:
#Estrutura do if..else
nota = float(input("Digite sua nota na disciplina:"))

if nota>= 6.0:
  print('Aprovado!')
else: # Atenção: Cuidado com a identação !
  print('Reprovado!')

In [ ]:
#Estrutura do if...elif( else + if )...else
idade = int(input("Digite sua idade"))
if idade <3:
  print(Bebê)
elif idade <10: # Atenção: Cuidado com a identação!
  print('Infantil')
elif idade <14:
  print('Junio')
elif idade <18:
  print('Adolescente')
elif idade <30:
  print('Jovem')
else:
  print('Adulto')

## **Exemplos tópico 7.Estruturas de Repetição**

In [ ]:
#Estrutura Laço While

senha = "54321"
leitura =" "

while (leitura != senha):
  leitura = input("Digite a senha:")
  if leitura == senha :
    print('Acesso liberado')
  else:
    print('Senha incorreta.Tente novamente')

In [ ]:
#Estrutura Laço While - Soma 5 valores

contador = 0 
somador = 0
while contador < 5:
  contador = contador + 1
  valor = float(input('Digite o '+str(contador)+'º valor:'))
  somador = somador + valor
print ('Soma = ',somador )

In [ ]:
#Laço for
#O range eh gerado por causa de uma sequencia numerica

s=0
for x in range(1,20,3):
  s = s+x
print('Soma = ', s)


Soma =  70


In [ ]:
Lista_notas= [3.4,6.6,8,9,10,9.5,8.8,4.3]

soma=0
for nota in Lista_notas:
  soma = soma+nota
media = soma/len(Lista_notas)
print('Média = ', ' {:.2f}'.format(media) )

In [ ]:
def CalcMedia(lista):
  soma=0
  for nota in lista:
    soma = soma+nota
  return soma/len(lista)

Lista_notas= [3.4,6.6,8,9,10,9.5,8.8,4.3]
media = CalcMedia(Lista_notas)
print('Media =', '{:.2f}'.format(media))

Media = 7.45


In [ ]:
def categoria(idade):
  if idade < 3:
    ctg = 'Bebê'
  elif idade < 10:
    ctg = 'Infantil'
  elif idade < 14:
    ctg = 'Junior'
  elif idade < 18:
    ctg = 'Adolescente'
  elif idade < 30:
    ctg = 'Jovem'
  else:
    ctg = 'Adulto'
    return ctg # Lembrar de identar o codigo corretamente; return dentro do else

idd = int(input("Digite sua idade:"))
print("Sua categoria é:", categoria(idd))   

Digite sua idade:10
Sua categoria é: None


In [ ]:
def categoria(idade):
  if idade < 3:
    ctg = 'Bebê'
  elif idade < 10:
    ctg = 'Infantil'
  elif idade < 14:
    ctg = 'Junior'
  elif idade < 18:
    ctg = 'Adolescente'
  elif idade < 30:
    ctg = 'Jovem'
  else: ctg = 'Adulto'
  return ctg

idd = int(input("Digite sua idade:"))
print("Sua categoria é:", categoria(idd)) 

Digite sua idade:23
Sua categoria é: Jovem


In [ ]:
def MaiorValor(lista):
  if len(lista) > 0:
    maior = lista [0]
  else:
    maior = 0;
  for valor in lista:
    if valor > maior:
      maior = valor
  return maior

ListaNotas = [3.4,6.6,8,9,10,9.5,8.8,4.3]
resultado = MaiorValor(ListaNotas)
print (resultado)

10


In [ ]:
def Leitura(lista,qtd):
  for i in range(1,qtd+1):
    lista.append(int(input("Digite o valor do elemento")))

ListaNotas = []
Leitura(ListaNotas,5)
print(ListaNotas)

In [ ]:
def cria():
  d = {}
  return d

def inclui(d):
  nome = input("Digite o nome a incluir: ")
  if nome in d:
    print("Nome já existe não pode ser incluido")
  else:
    fone = input("Digite o fone:")
    d[nome]=fone

def consulta(d):
  nome = input("Digite o nome a consultar: ")
  print("Telefone: ",d.get(nome,'Não disponivel'))

def altera(d):
  nome = input("Digite o nome do fone a alterar: ")
  print("Telefone atual: ",d.get(nome,'Não disponivel' ))
  if nome in d:
    fone = input("Digite o novo fone: ")
    d[nome]=fone
    print("Telefone alterado!")
  else:
    print("Telefone não pode ser alterado !")

def exclui(d):
  nome = input("Digite o nome a excluir: ")
  if nome in d:
    del d[nome]
    print("Nome e fone excluidos !")
  else:
    print("Nome Inexistente !")

def mostra(d):
  print("Agenda:")
  for nome in d.keys():
    print(nome,d[nome])

agenda = cria()
inclui(agenda)
inclui(agenda)
inclui(agenda)
consulta(agenda)
altera(agenda)
exclui(agenda)
mostra(agenda)


In [ ]:
agenda = cria()
opc = 10
while opc!= 0:
  opc = int(input("Digite 0.Sair,1.INC,2.Con,3.Alt,4.Exc,5.Most:"))
  if opc ==1:
    inclui(agenda)
  elif opc == 2:
      consulta(agenda)
  elif opc == 3:
      aletra(agenda)
  elif opc == 4:
      exclui(agenda)
  elif opc == 5:
      mostra(agenda)
  elif opc == 0:
      print("Tchau,Tachu")
  else:
      print("Opção Inválida!")

In [ ]:
tempc = [23,18,32,16,21]
tempf = []
for i in tempc:
  tempf.append((i * 9/5) + 32)
print(tempc)
print(tempf)

[23, 18, 32, 16, 21]
[73.4, 64.4, 89.6, 60.8, 69.8]


In [ ]:
tempc = [23,18,32,16,21]
tempf = list(map(lambda x: (x * 9/5)+ 32,tempc))
print(tempc)
print(tempf)

[23, 18, 32, 16, 21]
[73.4, 64.4, 89.6, 60.8, 69.8]


In [ ]:
tempc = [23,18,32,16,21]
tempf = [(x*9/5)+ 32 for x in tempc]
print(tempc)
print(tempf)

[23, 18, 32, 16, 21]
[73.4, 64.4, 89.6, 60.8, 69.8]


In [ ]:
s = 'tokenizar'
stk = [x for x in s]
print(s)
print(stk)

tokenizar
['t', 'o', 'k', 'e', 'n', 'i', 'z', 'a', 'r']


## **Exemplos tópico 8.NumPy**

In [ ]:
import numpy as np

In [ ]:
a = np.array([12,34,26,18,10])
# ira cria uma matriz unidimensional
print(a)
print(a.dtype)

[12 34 26 18 10]
int64


In [ ]:
a1 = np.array([1, 2, 3], dtype = np.float64)
# cria um array como float de 64 bits
print(a1)
print(a1.dtype)

a2 = np.array([1, 2,3], dtype = np.int32)
# cria um array como float de 64 bits
print(a2)
print(a2.dtype)

[1. 2. 3.]
float64
[1 2 3]
int32


In [ ]:
a3 = np.array([1.4, 3.6, -5.1, 9.42, 4.999999, 4.4, -9.0 ])
# tranformar tipo de dados de arrays
print(a3)
print(a3.dtype) # ira mostrar o array definido na variavel a3

a4 =a3.astype(np.int32)
# tranformar float para int ( os valores são truncados)
print(a4)
print(a4.dtype) # mostra o array a3 transformado para int na variavel a4

a5 = np.array([1, 7, 8, 9])
print(a5)
print(a5.dtype)

a6 = a5.astype(float)

#realizando de forma inversa

print(a6)
print(a6.dtype)


[ 1.4       3.6      -5.1       9.42      4.999999  4.4      -9.      ]
float64
[ 1  3 -5  9  4  4 -9]
int32
[1 7 8 9]
int64
[1. 7. 8. 9.]
float64


In [ ]:
b = np.array([[7,98,23], [11,27,4], [999,34,23]])
print(b)

[[  7  98  23]
 [ 11  27   4]
 [999  34  23]]


In [ ]:
import numpy as np
c = np.empty([3,2], dtype = int)
print(c)

[[94238670315248              0]
 [             0              0]
 [             0              0]]


In [ ]:
d = np.zeros([4,3]) # ira criar uma matriz 4x3 com valores = 0 
print(d)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
e = np.ones([2,2]) # ira criar uma matriz 2x2 com valores = 1
print(e)

[[1. 1.]
 [1. 1.]]


In [ ]:
f = np.eye(5) # ira criar uma matriz quadrada com a diagonal com valores =1 e os outros valores =0
print(f)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
g = np.random.random((5))
print(g)

[0.02213139 0.8005764  0.31434192 0.22655447 0.84212235]


In [ ]:
g2= np.random.randn((5))
print(g2)

[-0.3039127  -1.83266771  0.65960536 -0.41693885  0.59017652]


In [ ]:
h =np.floor(10*np.random.random((3,4)))
print(h)
h = (10*np.random.random((3,4)))
print (h)
h = np.floor(h)
print (h)

[[0. 2. 2. 8.]
 [6. 4. 6. 7.]
 [3. 8. 4. 5.]]
[[2.90900427 1.73789682 1.48506638 9.45436004]
 [3.53880952 8.62840633 4.56945215 9.98217553]
 [5.71361472 8.23986035 6.92162039 1.93122764]]
[[2. 1. 1. 9.]
 [3. 8. 4. 9.]
 [5. 8. 6. 1.]]


In [ ]:
gnr = np.random.default_rng(0)
i = gnr.random(3)
print(i)

[0.63696169 0.26978671 0.04097352]
